### ISSUE TITLE
Add utilities for matching between participants

### ISSUE THREAD

**Issue by arokem** [richford/AFQ-Insight#106]
To create quasi-experiments based on certain match characteristics in large datasets. 

@36000 has written some code to get this started. 

Maybe this should go into a new module called `match`? It looks like the convention so far is for modules to be named as imperative verbs ("cross_validate", "transform", "plot").

**Comment by richford** [comment]
Agreed! I think `match` would be a good home for it. @36000, maybe you could get this started with a WIP PR by extracting the matching code you are using and modularizing it into various functions. I'm happy to help if you get a WIP PR started.

**Comment by richford** [comment]
Closed by #107
