### ISSUE TITLE
Matching fails when dataframe has non-numeric indices

### ISSUE THREAD

**Issue by richford** [richford/AFQ-Insight#111]
`mahalonobis_dist_match` fails when the input dataframe has a non-integer index (e.g. subject IDs). I believe [this line](https://github.com/richford/AFQ-Insight/blob/a82d4eaab88b031f8aadfbd3476ebeb7b0a18718/afqinsight/match.py#L119) should use `iloc` instead of `loc`.

**Comment by arokem** [comment]
@richford : was this really closed by #112? Or should we reopen it?

**Comment by richford** [comment]
Yep, I snuck it in there. See the change on [this line](https://github.com/richford/AFQ-Insight/blob/56fcf7f5b3c32fa65f082ef860bf3900bf46b4fc/afqinsight/match.py#L119). Apologies for not doing a separate branch/PR.
