### ISSUE TITLE
Tensorflow datasets => CNN

### ISSUE THREAD

**Issue by arokem** [richford/AFQ-Insight#114]
I've been working with the `tf_models` module and trying to feed in a tensorflow dataset into these models. I am running into some issues that are replicated in this self-contained example: 

https://gist.github.com/arokem/db5d1b212268ab65effaa173f603cdfe

I must be doing something wrong, but I've tried a lot of different things already: 

1. changing the `input_shape` to all kinds of other things. 
2. Initializing the dataset using `from_tensors` and `from_generator` instead of `from_tensor_slices`. 
3. Turning batching off. 

And probably some other things that I don't remember right now. What am I missing?

**Comment by richford** [comment]
Thanks! The `batch` method that you're using in the gist isn't an inplace operation so one has to do
```
dataset = dataset.batch(32)
```

**Comment by arokem** [comment]
Sorry. I am wrong again. But try this: 

```
train_dataset = train_dataset.batch(32)
model.fit(train_dataset, epochs=100, validation_data=val_dataset)
```

Something about passing validation data?

**Comment by arokem** [comment]
Oh - I see - I need to batch the validation data as well! 

That might work.

**Comment by arokem** [comment]
Indeed, in this case: 

```
train_dataset = train_dataset.batch(32)
val_dataset = val_dataset.batch(32)

model.fit(train_dataset, epochs=100, validation_data=val_dataset)
```

Sorts it out. In this example, and in the original use-case.

**Comment by richford** [comment]
🥳
