### ISSUE TITLE
TypeError: minimize_proximal_gradient() got an unexpected keyword argument 'step_size'

### ISSUE THREAD

**Issue by 36000** [richford/AFQ-Insight#29]
Running this line I get the error "TypeError: minimize_proximal_gradient() got an unexpected keyword argument 'step_size'"
https://github.com/richford/AFQ-Insight/blob/a6838a1c969720872260b2e4917128dabae96965/afqinsight/insight.py#L355
I believe step_size has been replaced by step: https://github.com/openopt/copt/blob/0c1d1c4ea6beb22a3e47f69dc65f0d49bc1babf7/copt/proximal_gradient.py#L80

**Comment by richford** [comment]
Thanks @36000. This should be fixed with [c8f4c46fb](https://github.com/richford/AFQ-Insight/commit/c8f4c46fb47b77f794407f8f7b312f9700bbc8c7). Could you try again on the latest master branch?

**Comment by 36000** [comment]
Yes! Thanks, that fixed it.
