### ISSUE TITLE
Add sparse group regression problem generator

### ISSUE THREAD

**Issue by richford** [richford/AFQ-Insight#36]
`datasets.py` has the `make_sparse_group_classification` function which is a sparse group extension of `sklearn.datasets.make_classification`. We should also make a sparse group regression problem generator

**Comment by richford** [comment]
Oops, @mnarayan, I'm just realizing that I merged #42 too early and there were still some things that you wanted to do in that PR. I'll reopen this. When you're ready to make those changes, can you open a new PR to address this?

**Comment by mnarayan** [comment]
@richford I will add to those changes with a new PR.

**Comment by richford** [comment]
Closed via #42.
