### ISSUE TITLE
Visualize coefficient regularization paths

### ISSUE THREAD

**Issue by mnarayan** [richford/AFQ-Insight#45]

**Comment by richford** [comment]
@mnarayan, what do you think. Should this be migrated over to [groupyr](https://github.com/richford/groupyr) or should it stay here? My vote would be to migrate to groupyr. But perhaps we want to have AFQ specific visualizations of the bundle properties.

**Comment by mnarayan** [comment]
I vote for migration. What I am implementing now wouldn't be AFQ specific.

**Comment by richford** [comment]
Migrating to https://github.com/richford/groupyr/issues/9
