### ISSUE TITLE
Add a `GroupMeanTransformer`

### ISSUE THREAD

**Issue by arokem** [richford/AFQ-Insight#78]
We often want mean value in each group. Would be great to have a `GroupMeanTransformer` that gives us that easily.

**Comment by richford** [comment]
Maybe this should go in groupyr since it's more general? Then we could write a small wrapper in AFQ-Insight with tractometry-specific keywords.

**Comment by arokem** [comment]
👍 I can see someone wanting to do a group-wise transform before running a regression in groupyr for other kinds of data. On further thought, I think that maybe a more general API would be one that applies a callable to each group that reduces the values in each group to one value. So, a `GroupReduceTransformer`.

Here, I think that it would be great if the `AFQDataFrameMapper` knew how to do that across a nodes dataframe, possibly also exposing this as part of the `load_afq_data` function API. WDYT?
