### ISSUE TITLE
The output from load_afq_data is getting pretty busy

### ISSUE THREAD

**Issue by richford** [richford/AFQ-Insight#81]
`load_afq_data` already returns a tuple with up to 8 elements. Depending on how we resolve #78, this might climb up to 9 elements. This is too much and I often forget the order of the results. How should we simplify the returned result:

- Return a dict with keys `X`, `subjects`, `groups`, etc.
- Return a [namedtuple](https://docs.python.org/3/library/collections.html#namedtuple-factory-function-for-tuples-with-named-fields). See [`os.stat`](https://docs.python.org/3/library/os.html#os.stat) for an example implementation from the standard library.
- Leave `load_afq_data` as is but also provide an `AFQDataLoader` class with attributes for each return value.

I'm partial to the namedtuple since it can be unpacked like a regular tuple so it would be backwards compatible. But we could also access the fields by name, much like a class instance's attributes. Kind of the best of both.

@arokem WDYT?

**Comment by arokem** [comment]
+1 for the namedtuple
